// JavaScript Document
$(function(){
	$(".t3").tap(function(){
		$(".hideDiv").show()
		$(".t_con1").show()
		$(".t_con1").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t4").addClass("orange")
		$(".t5").addClass("orange")
		$(".t6").addClass("orange")
		$(".t13").addClass("orange")
		})
	$(".t4,.t6").tap(function(){
		$(".hideDiv").show()
		$(".t_con2").show()
		$(".t_con2").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(".t3").addClass("orange")
		$(".t4").addClass("orange")
		$(".t5").addClass("orange")
		$(".t6").addClass("orange")
		})
	$(".t5").tap(function(){
		$(".hideDiv").show()
		$(".t_con5").show()
		$(".t_con5").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t15").addClass("orange")
		$(".t3").addClass("orange")
		$(".t4").addClass("orange")
		$(".t6").addClass("orange")
		})
	$(".t15").tap(function(){
		$(".hideDiv").show()
		$(".t_con15").show()
		$(".t_con15").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).siblings("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t5").addClass("orange")
		})
	$(".t17").tap(function(){
		$(".hideDiv").show()
		$(".t_con17").show()
		$(".t_con17").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).siblings("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t27").addClass("orange")
		$(".t37").addClass("orange")
		$(".t47").addClass("orange")
		})
	$(".t34").tap(function(){
		$(".hideDiv").show()
		$(".t_con34").show()
		$(".t_con34").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).siblings("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t24").addClass("orange")
		$(".t44").addClass("orange")
		})
	$(".t43").tap(function(){
		$(".hideDiv").show()
		$(".t_con43").show()
		$(".t_con43").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t41").addClass("orange")
		$(".t42").addClass("orange")
		$(".t44").addClass("orange")
		})
	$(".t44").tap(function(){
		$(".hideDiv").show()
		$(".t_con44").show()
		$(".t_con44").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t24").addClass("orange")
		$(".t34").addClass("orange")
		$(".t41").addClass("orange")
		$(".t42").addClass("orange")
		$(".t43").addClass("orange")
		})
	$(".t55").tap(function(){
		$(".hideDiv").show()
		$(".t_con55").show()
		$(".t_con55").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t56").addClass("orange")
		})
	$(".t66").tap(function(){
		$(".hideDiv").show()
		$(".t_con66").show()
		$(".t_con66").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t56").addClass("orange")
		$(".t67").addClass("orange")
		})
	$(".t56").tap(function(){
		$(".hideDiv").show()
		$(".t_con56").show()
		$(".t_con56").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t55").addClass("orange")
		$(".t66").addClass("orange")
		})
	$(".t67").tap(function(){
		$(".hideDiv").show()
		$(".t_con67").show()
		$(".t_con67").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(".t63").removeClass("orange")
		$(this).addClass("orange")
		$(".t66").addClass("orange")
		$(".t77").addClass("orange")
		$(".t87").addClass("orange")
		$(".t97").addClass("orange")
		})
	$(".t77").tap(function(){
		$(".hideDiv").show()
		$(".t_con77").show()
		$(".t_con77").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(".t73").removeClass("orange")
		$(this).addClass("orange")
		$(".t67").addClass("orange")
		$(".t78").addClass("orange")
		$(".t79").addClass("orange")
		$(".t80").addClass("orange")
		$(".t87").addClass("orange")
		$(".t97").addClass("orange")
		})
	$(".t73").tap(function(){
		$(".hideDiv").show()
		$(".t_con73").show()
		$(".t_con73").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).siblings("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t63").addClass("orange")
		$(".t83").addClass("orange")
		$(".t93").addClass("orange")
		})
	$(".t78").tap(function(){
		$(".hideDiv").show()
		$(".t_con78").show()
		$(".t_con78").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(".t73").removeClass("orange")
		$(this).addClass("orange")
		$(".t77").addClass("orange")
		$(".t79").addClass("orange")
		$(".t80").addClass("orange")
		})
	$(".t87").tap(function(){
		$(".hideDiv").show()
		$(".t_con87").show()
		$(".t_con87").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(this).siblings("li").removeClass("orange")
		$(this).addClass("orange")
		$(".t77").addClass("orange")
		$(".t67").addClass("orange")
		$(".t97").addClass("orange")
		})
	$(".t81,.t84").tap(function(){
		$(".hideDiv").show()
		$(".t_con81").show()
		$(".t_con81").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(".t87").removeClass("orange")
		$(".t81").addClass("orange")
		$(".t82").addClass("orange")
		$(".t83").addClass("orange")
		$(".t84").addClass("orange")
		})
	$(".t96,.t98").tap(function(){
		$(".hideDiv").show()
		$(".t_con96").show()
		$(".t_con96").siblings(".t_con").hide()
		h=$("#h").height()+30
		$(".hideDiv").css("height",h)
		$(this).parent().siblings().children("li").removeClass("orange")
		$(".t96").addClass("orange")
		$(".t97").addClass("orange")
		$(".t98").addClass("orange")
		$(".t99").addClass("orange")
		})
	$(".btnsDiv a").tap(function(){
		$(".hideDiv").hide()
	})
	var btn,btnIndex;
	$(".tishi").on("tap",function(){
		return btn=$(this);	
	});
	$(".cureBtns").on("tap",function(){
		var	valText=$(this).parents(".t_con").find("input").val();
		if(btn.html() != ""){
			btn.find("p i").html(valText);
		}else{
			btn.html(valText);
		}
		$(".hideDiv").hide();
	});
		
})