var str='<footer>'
	+'<div class="container">'
	+'<div class="row">'
	+'<div class="col-md-5 copy-right">'
	+'<p><img src="images/gift-design.png" alt="" /></p>'
	+'</div>'
	+'<div class="col-md-7 xh_down xh_down_di">'
	+'<ul class="clearfix saoma">'
	+'<li><a href="#"><i class="fa fa-comments"></i><p>睿艺微信</p></a></li>'
	+'<li><a href="#"><i class="fa fa-qrcode"></i><p>睿艺微博</p></a></li>'
	+'<li><a href="#"><i class="fa fa-facebook-square"></i><p>FACEBOOK</p></a></li>'
	+'</ul>'
	+'<div class="xh_downs">'
	+'<p class="xh_aList"><a href="#">联系我们</a> <a href="#">关于我们</a> <a href="#">人才招聘</a> <a href="#">优秀团队</a></p>'
	+'<p class="">地址：朝阳区苹果社区N区N栋   电话：400-019-0039</p>'
	+'<p>版权所有 @ 睿艺空间   京ICP备05039402号-11  京公网安备11010802016652号</p>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</footer>';
	document.write(str);