var str='<div class="top-bar">'
        +'<p class="text">'
        +'<a href="tel:400-019-0038"><i class="fa fa-phone"></i>400-019-0038</a>'
        +'</p>'
        +'</div>'
        +'<header class="clearfix">'
        +'<div class="logo">'
        +'<a href="#"><img src="images/u8.png" alt=""></a>'
        +'</div>'
        +'<nav class="navbar collapse" id="mobile-menu">'
        +'<ul class="nav navbar-nav">'
        +'<li class="active"><a href="index.html">首页</a></li>'
        +'<li>'
		+'<a href="#" data-toggle="dropdown">在线评估</a>'
		+'<ul class="dropdown-menu">'
        +'<li><a href="#">作品评估</a></li>'
        +'<li><a href="#">院校评估</a></li>'
        +'<li><a href="#">综合评估</a></li>'
        +'</ul>'
		+'</li>'
        +'<li class="dropdown">'
        +'<a class="dropdown-toggle" data-toggle="dropdown">艺术资讯</a>'
        +'<ul class="dropdown-menu">'
        +'<li><a href="#">设计类</a></li>'
        +'<li><a href="#">影视/动画</a></li>'
        +'<li><a href="#">纯艺术</a></li>'
        +'<li><a href="#">音乐类</a></li>'
        +'</ul>'
        +'</li>'
        +'<li class="dropdown">'
        +'<a class="dropdown-toggle" data-toggle="dropdown">院校·专业</a>'
		+'<ul class="dropdown-menu">'
		+'<li><a href="#">艺术院校</a></li>'
        +'<li><a href="#">专业介绍</a></li>'
        +'<li><a href="#">院校排名</a></li>'
        +'</ul>'
        +'</li>'
        +'<li class="dropdown">'
        +'<a class="dropdown-toggle" data-toggle="dropdown">作品集培训</a>'
        +'<ul class="dropdown-menu">'
        +'<li><a href="#">作品集培训</a></li>'
        +'<li><a href="#">申请</a></li>'
        +'</ul>'
        +'</li>'
        +'<li class="dropdown">'
        +'<a class="dropdown-toggle" data-toggle="dropdown">成功案例</a>'
        +'<ul class="dropdown-menu">'
        +'<li><a href="#">成功案例</a></li>'
        +'<li><a href="#">优秀作品</a></li>'
        +'</ul>'
        +'</li>'
		+'<li><a href="#">优秀作品</a></li>'
        +'<li><a href="#">艺术导师</a></li>'
		+'<li><a href="#">关于我们</a></li>'
        +'</ul>'
        +'</nav>'
        +'<div class="user">'
        +'<a href="#" class="dropdown-toggle">'
		+'<i class="fa fa-user"></i>'
		+'</a>'
        +'</div>'
        +'<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mobile-menu" aria-expanded="false">'
        +'<span class="icon-bar"></span>'
        +'<span class="icon-bar"></span>'
        +'<span class="icon-bar"></span>'
		+'</button>'
        +'</header>';
		document.write(str);